[FIX] project_enterprise_hr: build error when hr not installed
Steps to reproduce:
- start test_auto_schedule_flex_resource when hr not installed.
=> `AttributeError: 'res.users' object has no attribute 'action_create_employee'

Source:
- action_create_employee comes from hr, but the test is in project_enterprise

Fix:
- tests related to hr moved to project_enterprise_hr

closes odoo/enterprise#96365

Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>