[FIX] hr_recruitment_integration_monster: give valid attribute name
An error occurs while preparing monster data because in code mistakenly
uses the attribute name 'is_flexible_hours' instead of the correct attribute
name 'flexible_hours' to check the flexible hours of the resource calendar.

AttributeError: 'resource.calendar' object has no attribute 'is_flexible_hours'

To resolve this issue, Give a valid attribute name 'flexible_hours' instead of
'is_flexible_hours'.

Sentry-6150854320

closes odoo/enterprise#76734

X-original-commit: e7730be4efbf001769562b35011053351ad531d6
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>