[FIX] l10n_mx_{hr_payroll}_localisation: prevent error while removing end date
The system failed to retrieve `worked_days.payslip_id.date_to` because user
remove end period

Steps to Reproduce:
1. Switch to My Mexican Company.
2. Go to Payroll > click Payslips > To Pay > Click New.
3. Select Employee from the selection
4. Remove end period (Right One).

Error:
TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.date'

Solution:
Ensure that if worked_days.payslip_id.date_to, start_date, end_date are not
present then continue the flow

Sentry - 6473512002

closes odoo/enterprise#86662

X-original-commit: da76d6f74260cc7361049a632038a47ceb6b1ce4
Signed-off-by: Jurgen Gjini (jugj) <jugj@odoo.com>
Signed-off-by: Krishna Arvindkumar Patel (krip) <krip@odoo.com>