[FIX] hr_referral: prevent error on installing module
Currently a ParseError is arising when the user installs the 'hr_referral'
module after deleting all Stages in Recruitment/Configuration.

Steps to reproduce:
- Install 'hr_recruitment' application (without demo data).
- Delete all 'Stages' in Recruitment > Configuration
- Now install 'hr_referral' module

Traceback:
Exception: Cannot update missing record 'hr_recruitment.stage_job3'

ParseError
while parsing /home/odoo/src/enterprise/saas-18.1/hr_referral/data/data.xml:93, somewhere inside
<record model="hr.recruitment.stage" id="hr_recruitment.stage_job3">
            <field name="use_in_referral">True</field>
        </record>

The error occurs because the user deleted all 'Stages' in Recruitment, and
then tried to install the other module.

This commit solves the above issue by using 'forcecreate' False to bypass
record creation if it violates checks.

https://github.com/odoo/odoo/blob/f5378fadf910d193cbb44a4d1c10a5a15d8b9a51/odoo/tools/convert.py#L364

sentry-5731062091

closes odoo/enterprise#82632

X-original-commit: 60e7d3c5de32451c6ef3bb9cdd058bbd21a87a97
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>