[FIX] project_account_budget: prevent error while adding project update
Currently an issue is generated when the project user tries to add
a project update.

Steps to produce an error:
- Install the 'project_account_budget' module with demo data.
- Log in with the demo user
- Go to Project and open the dashboard of the Home Construction project
- Click new »> error occurs

Error
```
QWebError
Error while rendering the template:
    KeyError: 'revenues'
    Template: project.project_update_default_description
```

This issue occurs due to:
 - The reference commit [1] enhances the project update form description by
   enabling the display of profitability even without the sale timesheet.
- With commit [1], code was added to set the `profitability_values` to an
  `empty dictionary ({})` and `show_profitability` to `False` (see [2]) , since
  the demo user does not belong to the `project.group_project_manager`
  group (see [3]).
- In the `project_account_budget` module, the value of `show_profitability`
  is updated and set to True because the total_budget_amount is present
  in the project (see [4]).
- In the template `project_update_default_description` rendering, the
  `profitability` is accessed when `show_profitability` is `True`. However,
  since `profitability` is an empty dictionary, attempting to access the key
  will result in an error (see [4]).

This commit fixes the above issue by preventing the recalculation of
`show_profitability`, as it is already set based on whether `profitability`
data is available or not.

[1]: https://github.com/odoo/odoo/commit/e81af984aabe61defa0932b7890ab373fe3c8e2a
[2]: https://github.com/odoo/odoo/blob/385d8473952eeaa9dcc7740bacfc2c9cbdc2d1e2/addons/project/models/project_update.py#L114-L126
[3]: https://github.com/odoo/odoo/blob/385d8473952eeaa9dcc7740bacfc2c9cbdc2d1e2/addons/project/models/project_project.py#L1111-L1112
[4]: https://github.com/odoo/odoo/blob/385d8473952eeaa9dcc7740bacfc2c9cbdc2d1e2/addons/project/views/project_update_templates.xml#L26-L31

Sentry-6915109069,6981931420

closes odoo/enterprise#98441

Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>