[FIX] partner_commission: prevent error on installing module
Currently, a ParseError is arising when the user installs the 'partner_commission'
module after deleting the 'Services' in Product Categories/Configuration.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Product Categories > Delete 'Services'
- Now install 'partner_commission' module

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/enterprise/saas-18.4/partner_commission/data/data.xml:3, somewhere inside
<record id="product_commission" model="product.product">
        <field name="name">Commission</field>
        <field name="purchase_ok" eval="True"/>
        <field name="categ_id" ref="product.product_category_services"/>
        <field name="type">service</field>
    </record>

The error occurs because the user deleted 'Services' in Product Categories, and
then tried to install the other module.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6754387015

closes odoo/enterprise#90979

X-original-commit: e8acdf50759f4606b1bef3e834f12a4688e76cf1
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>