[FIX] l10n_tr_hr_payroll: restrict field to hr group
The test test_employee_fields_groups crashed with:

AccessError: The fields “l10n_tr_is_net_to_gross”, which you are trying to read, are not available for employee public profiles.

This field exist without HR group restriction as a result, a non-HR internal user calling .read([]) triggered the AccessError.

This commit adds `groups="hr_payroll.group_hr_payroll_user"` to this field so it is only accessible to HR users, resolving the error.

RB-231736

closes odoo/enterprise#94796

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>