[FIX] l10n_mx_edi: prevent error when adding CFDI Origin in credit notes
Currently, an error occurs when creating a customer credit note with a CFDI
Origin.

Steps to reproduce:

- Install the 'l10n_mx_edi' module and switch to 'ESCUELA KEMPER URGATE' company.
- Navigate to: Invoicing > Customers > Credit Notes > New.
- Set CFDI Origin to '01|E19C50D2-1292-5817-BDDE-2666967C7471' and click 'Save'.

Error:
TypeError: unhashable type: 'list'

Root Cause:
At [1], the code incorrectly uses relationado_data['03', []] instead of
relationado_data.get('03', []). The tuple ('03', []) is treated as a dictionary
key, which leads to an error.

Fix:
This commit ensures users can correctly set the CFDI Origin.

[1]:
https://github.com/odoo/enterprise/blob/14b31a3631a97dd61ebd662fb768485e5a509c2c/l10n_mx_edi/models/account_move.py#L500

sentry-6823395705

closes odoo/enterprise#94693

X-original-commit: 44f4001112cf214a8895fb552270fac725f7bdfa
Signed-off-by: Joren Van Onder (jov) <jov@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>