[FIX] pos_settle_due: prevent error on installing module
Currently a ParseError is arising when the user installs the 'pos_settle_due'
module after deleting the 'Services' in Product Categories/Configuration.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Product Categories > Delete 'Services'
- Now install 'pos_settle_due' module

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/enterprise/saas-18.2/pos_settle_due/data/pos_settle_due_data.xml:4, somewhere inside
<record id="product_product_settle" model="product.product">
            <field name="name">Settle Due</field>
            <field name="categ_id" ref="product.product_category_services"/>
            <field name="type">service</field>
            <field name="weight">0.00</field>
            <field name="available_in_pos">False</field>
            <field name="taxes_id" eval="[]"/>
        </record>

The error occurs because the user deleted 'Services' in Product Categories, and
then tried to install the other module.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6377659355

closes odoo/enterprise#84853

X-original-commit: 44c128095fc0b77a978c5a233409f4c75e7006d0
Signed-off-by: David Monnom (moda) <moda@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>