[FIX] l10n_au_hr_payroll: Add default value for medicare reduction
It is possible for a user to empty the value for `l10n_au_medicare_reduction`
from an employee's form. Since this field is used in the computation of
`l10n_au_tax_treatment_code`, doing so will trigger an error:
```
File "/home/odoo/src/enterprise/18.0/l10n_au_hr_payroll/models/hr_employee.py", line 347, in _compute_l10n_au_tax_treatment_code
    code += rec.l10n_au_medicare_reduction  # Sixth Character
TypeError: can only concatenate str (not "bool") to str
```

This error can also happen during upgrades, when employee records are created
before the module `l10n_au_hr_payroll` is loaded.

closes odoo/enterprise#78942

X-original-commit: eb03e55163ea1e2bd1fb7051af9847a3c67a1d87
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Agustín Castro Bugallo (agcb) <agcb@odoo.com>