[FIX] helpdesk_account: fix traceback when opening invoice from tickets in portal
Currently, a traceback occurs when the user opens an invoice
from the tickets in the portal.

Error:- "AttributeError: 'list' object has no attribute 'ids'"

This error is occurring from the below line

https://github.com/odoo/enterprise/blob/a2cfc7c223dfe915a1965d08c2e1f91cfeabe2f6/helpdesk_account/controllers/portal.py#L40-L47

Initially, we get the recordsets of invoices in values['invoices'].
But because of the recent changes from the below commit,
we get list of recordset values, from which we can access the value of invoice id

https://github.com/odoo/odoo/pull/174812/files#diff-3b907221102acd53c211a3a6b50b00543dcbbc865d50ef4451bea465f7300cbaR107-R112

Community PR:- https://github.com/odoo/odoo/pull/190062

sentry-6117277208

closes odoo/enterprise#75421

X-original-commit: dcec7584e050e91affc312608829925de2176990
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>