[FIX] l10n_ec_edi: prevent error when opening a preview of an invoice
Currently, an error occurs when opening a preview of an invoice without an
invoice date

Step to produce:

- Install the 'l10n_ec_edi' module (with demo data).
- Change a current company to 'EC Company', which has an 'Ecuador' country.
- Create a new invoice, add a customer name, payment terms and invoice line,
save the record,
- Click on the 'Preview' button (ensure that the invoice has no date).

TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.date'

An error occurs when the system attempts to calculate payment term days at [1],
with using an invoice date, but it is not available.

Link [1]: https://github.com/odoo/enterprise/blob/26aa95079af2a868c2991c7f19daee5328d5bb01/l10n_ec_edi/models/account_move.py#L440C22-L440C93

To resolve this issue, Provide a default day zero(0) for the payment term, if
invoice date is not available.

Sentry-6015854429

closes odoo/enterprise#77392

X-original-commit: 3f5dcaa5958276d7413a9d4417db742b172003a9
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>