[FIX] marketing_automation_whatsapp: prevent error on running automation
Currently an error occurs when trying to run whatsapp marketing automation test
more than once.

Steps to replicate:
* Install marketing_automation_whatsapp
* Setup whatsapp integration
* Marketing Automation > New > Start From Scratch > Add a new activity
* Select Activity Type as Whatsapp Message and a Whatsapp Template
* Launch a Test > Pick a contact > Launch > Run (Do this step twice)

Error:
ValueError: Expected singleton: marketing.trace(6, 4, 3, 2, 1)

Cause:
This error occurs because the variable `trace` contains multiple records, but
the `process_event` method is being called on the entire recordset.

Since `process_event` uses `self.ensure_one()`, it expects exactly one record,
and therefore raises an error at [1] when multiple records are passed.

Solution:
* Handle trace records one by one using a loop.

[1]: https://github.com/odoo/enterprise/blob/624b18bdb5dff0df4756c4e1d37a696631e57a05/marketing_automation_whatsapp/models/marketing_trace.py#L20

Sentry-6772553612

closes odoo/enterprise#92672

X-original-commit: 046f5a529c7a9917d5565087c400cf61be869a8c
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>