[FIX] hr_appraisal: new user can load demo data
Currently, an error occurs when a new user tries to load demo data in the
'Appraisal' module.

Steps to reproduce:
- Install 'hr_appraisal' module (without demo data)
- Create NEW user > Login with new user
- Open 'Appraisal' and Click 'Load Demo Data'

Traceback:
ParseError: <record id="calendar_event_appraisal_1" model="calendar.event" forcecreate="1">
            <field name="user_id" ref="base.user_admin"/>
            <field name="name">Appraisal of Emma Granger</field>
            <field name="partner_ids" eval="[(6,0,[ref('hr.work_contact_sj'), ref('hr.work_contact_mw'),                 ref('hr.work_contact_eg')])]"/>
            <field name="start" eval="(DateTime.now() + relativedelta(months=1)).strftime('%Y-%m-%d 07:00:00')"/>
            <field name="stop" eval="(DateTime.now() + relativedelta(months=1)).strftime('%Y-%m-%d 09:00:00')"/>
            <field name="res_model_id" ref="hr_appraisal.model_hr_appraisal"/>
            <field name="res_model">hr.appraisal</field>
            <field name="res_id" ref="hr_appraisal.hr_appraisal_1"/>
        </record>

ValueError: ParseError('while parsing /home/odoo/odoo/enterprise/hr_appraisal/data/scenarios/hr_appraisal_scenario.xml:561, somewhere inside\n<record id="calendar_event_appraisal_1" model="calendar.event" forcecreate="1">\n            <field name="user_id" ref="base.user_admin"/>\n            <field name="name">Appraisal of Emma Granger</field>\n            <field name="partner_ids" eval="[(6,0,[ref(\'hr.work_contact_sj\'), ref(\'hr.work_contact_mw\'),                 ref(\'hr.work_contact_eg\')])]"/>\n            <field name="start" eval="(DateTime.now() + relativedelta(months=1)).strftime(\'%Y-%m-%d 07:00:00\')"/>\n            <field name="stop" eval="(DateTime.now() + relativedelta(months=1)).strftime(\'%Y-%m-%d 09:00:00\')"/>\n            <field name="res_model_id" ref="hr_appraisal.model_hr_appraisal"/>\n            <field name="res_model">hr.appraisal</field>\n            <field name="res_id" ref="hr_appraisal.hr_appraisal_1"/>\n        </record>') while evaluating
'action = model._load_demo_data()'

This error occurs because the new user has not been granted administrative
rights.

This commit resolves the issue by granting the user superuser rights.

sentry-6110523247

closes odoo/enterprise#95622

X-original-commit: 7002450b64b9a5148f5eca826e9027f79a6def7a
Related: odoo/odoo#228790
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>