[FIX] hr_work_entry_attendance: prevent error on installing module
Currently a 'ParseError' arises when the user installs the
'hr_work_entry_attendance' module after deleting all 'Overtime Rules' in the
'Rulesets' Configuration.

Steps to reproduce:
- Install 'hr_attendance' module(without demo)
- Attendance > Configurations > Overtime Rulesets
- Delete all 'Overtime Rules' in 'Default Ruleset'
- Now install 'hr_work_entry_attendance' module

Traceback:
Exception: Cannot update missing record 'hr_attendance.hr_attendance_overtime_employee_schedule_rule'

ParseError
while parsing /home/odoo/src/enterprise/19.0/hr_work_entry_attendance/data/hr_attendance_overtime_rule_data.xml:4, somewhere inside
<record id="hr_attendance.hr_attendance_overtime_employee_schedule_rule" model="hr.attendance.overtime.rule">
            <field name="work_entry_type_id" model="hr.attendance.overtime.rule" eval="obj()._get_default_work_entry_type_id()"/>
        </record>

The error occurs because the user deleted all 'Overtime Rules' and then
installed the 'hr_work_entry_attendance' module. which requires particular
records.

This commit solves the above issue by using noupdate="1" and forcecreate="0" to
skip the creation of record if it doesn't exists.
https://github.com/odoo/odoo/blob/b794f0f332f473deb2c04eba60baf4761db3b508/odoo/tools/convert.py#L364-L366

sentry-7023182659

closes odoo/enterprise#99347

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>