[FIX] sign: prevent error on signing encrypted file
Currently an error occurs when signing an encrypted file with empty password.

Steps to replicate
* Install `Sign`
* Sign> Upload a pdf > Add following [pdf](https://drive.google.com/file/d/1M0_VzWLzv-lSZ-IlI9Zmx-M7jFGvtJJj/view?usp=sharing)>  Sign the document using `Sign now`
* Validate and send completed document

`AttributeError: 'NoneType' object has no attribute 'seek'`

Cause:
This occurs because [1] returns `None` to the variable `output` at [2] which in
turn passes the `None` value to [3] causing the error.

Error occurs in python 3.12+, because it does not throw an exception
in `_check_pdf_data_validity`.

Solution:
* Add a validation to prevent upload of unsupported files.

[1]: https://github.com/odoo/enterprise/blob/e7861f1ddef2fb9628eebca93942e64c73cc95fc/sign/models/sign_document.py#L242-L243
[2]: https://github.com/odoo/enterprise/blob/e7861f1ddef2fb9628eebca93942e64c73cc95fc/sign/models/sign_completed_document.py#L33-L34
[3]: https://github.com/odoo/odoo/blob/033c7a63bdf3d10d9d2c5084959fd34f52011bea/odoo/tools/pdf/signature.py#L51

Sentry-6784800544,6802557168

closes odoo/enterprise#93749

X-original-commit: 7c11f9fd1da0e0f09f6fe6872ec671def378b655
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>
Signed-off-by: Anshik Gopalbhai Brahmbhatt (agbr) <agbr@odoo.com>