[FIX] sale_subscription: ensure test is not date dependent
Before this commit, when test_uninvoiced_upsell_close_log was launched
in a year different than 2025, it would fail with the following error:

```
File "/data/build/enterprise/sale_subscription/tests/test_sale_subscription.py", line 2085, in test_uninvoiced_upsell_close_log
    action = subscription.prepare_upsell_order()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/sale_subscription/models/sale_order.py", line 1042, in prepare_upsell_order
    action = self._prepare_renew_upsell_order('7_upsell', upsell_msg_body)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/sale_subscription/models/sale_order.py", line 1012, in _prepare_renew_upsell_order
    order = self._create_renew_upsell_order(subscription_state, message_body)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/test_sale_subscription/models/sale_order.py", line 228, in _create_renew_upsell_order
    order = super()._create_renew_upsell_order(subscription_state, message_body)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/sale_subscription/models/sale_order.py", line 998, in _create_renew_upsell_order
    values = self._prepare_upsell_renew_order_values(subscription_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/project_sale_subscription/models/sale_order.py", line 40, in _prepare_upsell_renew_order_values
    res = super()._prepare_upsell_renew_order_values(subscription_state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/partner_commission/models/sale_order.py", line 72, in _prepare_upsell_renew_order_values
    values = super()._prepare_upsell_renew_order_values(subscription_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/sale_subscription/models/sale_order.py", line 1182, in _prepare_upsell_renew_order_values
    raise UserError(_('You cannot create an upsell for this subscription because it :\n'
odoo.exceptions.UserError: You cannot create an upsell for this subscription because it :
 - Has not started yet.
 - Has no invoiced period in the future.
```

runbot-task-230716

closes odoo/enterprise#92341

X-original-commit: aa9e6fc079d5907bec9ee00ea277f2da19a7a4ca
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>