[FIX] account_invoice_extract: handle multiple records in user_selected_box
The error occurred because multiple `iap.extracted.words` records matched the
search filter for `user_selected_box`, and the code tried to access `.word_text`
directly on the multi-recordset, which expects a singleton.

Error:
ValueError: Expected singleton: iap.extracted.words(35683, 35697)

Solution:
-Added `('word_text', '=', text_to_send['content'])` to the search domain to
ensure only matching record is returned.

sentry-6547557298

closes odoo/enterprise#84903

X-original-commit: 2b650a442bd3f7a11c0962d8e597159d55842cc3
Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>