[FIX] planning: prevent error on missing end date
Currently an error occurs when user tries to remove end date on slot.

Steps to replicate:
- Install `planning`.
- Create a new planning slot and click on a slot template at the top.
- Remove the end date (rightmost) and click elsewhere.

Error:
```
 File /home/odoo/odoo18/enterprise/planning/models/planning.py, line 423, in _compute_template_id
    if slot._different_than_template():
 File /home/odoo/odoo18/enterprise/planning/models/planning.py, line 439, in _different_than_template
    slot_time = self[slot_field].astimezone(pytz.timezone(self._get_tz()))
AttributeError: 'bool' object has no attribute 'astimezone'
```
Cause:
- When the end date was removed, [compute] was triggered, calling the
  `_different_than_template()` method, which iterates through the fields in the
  slot template.
- Since the user removed `end_datetime`, self['end_datetime'] became false and
  caused the error at line [1].

Solution:
- Returned from the function call when `end_datetime` is false.

[compute]: https://github.com/odoo/enterprise/blob/745c1cc0e06f5e0578ec4383439f8be2419adb6b/planning/models/planning.py#L418-L426

[1]: https://github.com/odoo/enterprise/blob/745c1cc0e06f5e0578ec4383439f8be2419adb6b/planning/models/planning.py#L438

No ID

closes odoo/enterprise#102909

X-original-commit: 6cd6a0a78bed4a61449827ec655b65de8cfbf7a6
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>