[FIX] l10n_id_hr_payroll:prevent error when payslip period date is removed
Currently, An Error occurs on removing the **Date To** or **Date From** value from a payslip's period.

**Steps to Reproduce**
1) Install **l10n_id_hr_payroll module**.
2) Create a new **Pay-Slip**.
3) Remove **Date** from **Period**

**Error:**
`AttributeError: 'bool' object has no attribute 'month'`

**Root Cause:**
The `_compute_l10n_id_include_pkp_ptkp` method at [1] assumes that `date_to` and `contract_id.date_end` are always set and valid.
If either of them is missing (False), accessing `.month` or `.year` causes an error.

[1] - https://github.com/odoo/enterprise/blob/34aa0ffb82c1bd7c90b4cb161ea515f2cad8e65f/l10n_id_hr_payroll/models/hr_payslip.py#L87

**Solution:**
This commit prevents the computation from failing when `slip.date_to` and `slip.contract_id.date_end`
fields are unset by adding a conditional check to ensure that both fields are valid date objects before
accessing their `.month` and `.year` attributes.

sentry-6608982173

closes odoo/enterprise#86863

X-original-commit: b32aab911a349fd04ffab0eb40a2ec32e41ac6fc
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Het Patel (path) <path@odoo.com>