[FIX] website_helpdesk: prevent error when archiving multiple teams linked to different websites
Currently, an error occurs when archiving multiple helpdesk teams linked to
different websites.

Steps to reproduce:
- Install the website_helpdesk module.
- Go to Website, Configuration > Websites and create two websites (W1 and W2).
- Go to Helpdesk, Configuration > Helpdesk Teams > create two teams (T1 and T2).
- Enable the Website Form (under Help Center), assign W1 to T1 and W2 to T2.
- Return to the list view, select both teams, and attempt to archive them.

Error:
ValueError: Expected singleton: website(3, 1)

Root Cause:
At [1], the code incorrectly uses with_website.website_id.id, when multiple
websites are involved, this leads to an error.

Fix:
This commit prevents errors and ensures that users can archive multiple helpdesk
teams linked to different websites

[1]:
https://github.com/odoo/enterprise/blob/8b72fdef63f634ccf436b49adbac5c1f9358c127/website_helpdesk/models/helpdesk.py#L102

sentry-6867906123

closes odoo/enterprise#95621

X-original-commit: 87a07870bbc0c7c10acfaa3c5643436476ba1697
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>