[FIX] l10n_cl_edi: remove unnecessary `decode('utf-8')`
Issue:
The invoice XMLs having special characters like "Ó" received in DTE emails will trigger a traceback.

Cause:
`.decode('utf-8')` will try decoding the bytes in utf-8 but Ó is not UTF-8 so there is a traceback:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 1734: invalid continuation byte
```
In any case it crashes at the next line: `xml_content = etree.fromstring(xml_dte)` because the XML specifies the encoding (i.e. unicode) but the true encoding is `utf-8` so an error is raised:
```
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

Solution:
Remove `.decode('utf-8')` when decoding. The method `fromstring` accepts bytes and will use the encoding specified in the XML.

opw-5124661

closes odoo/enterprise#96580

X-original-commit: 4d1cc7d57f2fb47218944774523ba674a12462ce
Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>
Signed-off-by: Mathieu Coutant (mcou) <mcou@odoo.com>