[FIX] sale_subscription: prevent error while creating invoice of subscription
Currently, an error is produced while creating an invoice for a subscription
order with combo products, and it can be triggered in two different ways.

1. Directly create an invoice.
    - Create and confirm a subscription with a combo product.
    - Create an invoice for this subscription and try to confirm it.
    - Validation error shown in display and error generated in log

2.  When cron "Payment: Post-process transactions" trigger:
    - Enable the Automatic Invoice option in the Subscription settings.
    - Activate a demo payment provider (e.g. Demo: Payment Provider).
    - Create and confirm a subscription that includes a combo product.
    - Click on "Pay" to process the subscription payment.
    - An error occurs when the above-mentioned cron is triggered, and it
      tries to create an invoice for a subscription order.

Error: `new row for relation "account_move_line" violates check constraint
 "account_move_line_check_accountable_....`

This issue arises during the creation of an account move line for deferred
entries for the 'Combo Product' column of the original invoice (subscription):
- At [1], `deferred_start_date` and `deferred_end_date` were added
  to all invoice line values within `_prepare_invoice_line` used to create
  the original invoice
- Then, at [2], during confirmation of the `original invoice`, the code
  attempts to generate `deferred entries` for for move where any move
  lines that has a `deferred_start_date`
- At code line [3], during the generation of deferred entries, an account
  move line is created without an associated `account_id`
- During `display_type` computation at [4], `line.move_id.is_invoice()`
  evaluates to `False`. As a result, the line is assigned a `display_type`
 as a 'product'.
- Since `display_type` is 'product' and `account_id` is missing, it violates
  the following check constraint at [5]:
 `CHECK(display_type IN ('line_section', 'line_note') OR account_id IS NOT NULL)`

This commit fixes the issue by preventing the addition of the
`deferred_start_date` and `deferred_end_date` keys for invoice lines
whose corresponding sale order lines have products of type 'combo' at [1].

[1]: https://github.com/odoo/enterprise/blob/9642f7d8026149a6524e036c523b65ccbdf17258/sale_subscription/models/sale_order_line.py#L448-L449
[2]: https://github.com/odoo/enterprise/blob/9642f7d8026149a6524e036c523b65ccbdf17258/account_accountant/models/account_move.py#L113-L114
[3]: https://github.com/odoo/enterprise/blob/9642f7d8026149a6524e036c523b65ccbdf17258/account_accountant/models/account_move.py#L309
[4]: https://github.com/odoo/odoo/blob/9ec4e0d3c5f1aaff0b36dc5def1e69b8285c3be1/addons/account/models/account_move_line.py#L480-L484
[5]: https://github.com/odoo/odoo/blob/9ec4e0d3c5f1aaff0b36dc5def1e69b8285c3be1/addons/account/models/account_move_line.py#L451

sentry-6763423503

closes odoo/enterprise#94988

X-original-commit: 49d0c97ef08656744950ec4ec0f40f731ee80056
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>