[FIX] databases: ensure value in non-stored many2many compute method
Versions
--------
- 19.0+

Steps
-----
1. Go to Databases;
2. open a new project;
3. enter any name, hosting provider & URL;
4. under User Management, click on "Add a user".

Issue
-----
Traceback:
> ValueError: Compute method failed to assign databases.manage_users.wizard(<NewId 0x71e8c0d8fd80>,).everywhere_user_ids

Cause
-----
The `_compute_everywhere_user_ids` method computes the value of a
non-stored field. Consequently, every record in `self` needs have some
value assigned to `everywhere_user_ids` during the compute, but
currently, if the `database_ids` field is empty, `continue` is used
without assigning a value.

Solution
--------
If the record doesn't have any known `database_ids`, set
`everywhere_user_ids` to `None`.

opw-5170587

closes odoo/enterprise#99200

Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>