[FIX] account_followup: prevent error when executing follow-up process
When clicking the 'Process Follow-ups' button after creating a due invoice,
a traceback could occur due to missing data on the related records.

Steps to reproduce:
- Install 'account_followup' module(without demo)
- Go to 'Follow-up Levels' and enable SMS in '15 Days'
- Create an invoice with Invoice Date(2 months ago) and Payment terms: '15 Days'
- Now, click on the selected customer and fill in all important details
- In the action button, click 'Process Follow-ups'

Traceback:
KeyError: 'mobile'

ValueError: KeyError('mobile') while evaluating
'if records:\n                    action = records.action_manually_process_automatic_followups()'

The mobile field was removed from 'res.partner' (see related commit), but it
was not removed from here. This commit cleans it up to avoid referencing a
non-existent field.

commit- https://github.com/odoo/odoo/commit/6b820eb6fc6f782ba6a83d605d87b4a1dd2a87be

sentry-6720070075

closes odoo/enterprise#89588

X-original-commit: c32b729525542731a4af8bbf917bad90134dd668
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>