[FIX] sale_shopee: raise UserError if no Shopee shop linked to picking
Steps to reproduce the bug:
- Create a storable product “P1”
- Create a delivery order with one unit of P1, not linked to any sale
 order
- Go to the delivery order list view
- Select the created delivery order
- Click on Action → Fetch shipping label

Problem:
A traceback is triggered:

```
ValueError: ValueError('Expected singleton: shopee.shop()') while
evaluating
'records._fetch_shipment_label()'

The above server error caused the following client error:

```

The `_fetch_shipment_label` function expects at least one item, but
we don't check it via a user error, because we're supposed to call
`_sync_shopee_pickings` instead, where all these filtering and checks
are done

opw-4812360

closes odoo/enterprise#87778

X-original-commit: e0feb671fa57b38c71bc13b85ab889075df3735c
Signed-off-by: Morgane Demesmaeker <edm@odoo.com>