[FIX] account_accountant: fix payment state test for draft payments
The `test_bill_state_change_on_payment_state` is throwing an exception.
```
self.assertEqual(payment.invoice_ids.payment_state, 'not_paid')
AssertionError: 'paid' != 'not_paid'
- paid
+ not_paid
```

The test was incorrectly expecting invoice `payment_state` to always be
`not_paid` when payment is reset to draft, but behavior differs based on whether
`accountant` module is installed or not.

- With `accountant`: Payment has no move_id (no journal entry created by
default), so when drafted, `invoice.matched_payment_ids` filters exclude it,
resulting in 'not_paid' state.

- Without `accountant`: Payment has move_id (journal entry auto-created) so
filter conditions fail (`not p.move_id` is `False`), and invoice stays `paid`
due to existing reconciliations in `draft` state.

Test was introduced here:  https://github.com/odoo/enterprise/pull/100834/commits/402bd85af79fa68fa2cb957d40307edf62f7525c
Commits that introduced the behavior change:
https://github.com/odoo/odoo/pull/182390/commits/b572fcd78289013f28f11157b1bfbb75c9ea7344
https://github.com/odoo/odoo/blob/57f1053b031f293c6cd8dc8f590dccda4fb3e665/addons/account/models/account_move.py#L1308-L1314

Fix:
Updated test to expect correct state based on `accountant` installation.

Runbot: https://runbot.odoo.com/odoo/error/234573
Runbot error: 234573

closes odoo/enterprise#101248

X-original-commit: d9adfd9a5805075f1b4f5a87b8bd0d4e9fecab41
Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>