[FIX] pos_iot: prevent error when assigning scanner device
The error occurs because `append()` is used on the Many2many field
`iface_scanner_ids` in `pos_config`, which is not allowed.

Traceback:
AttributeError: 'iot.device' object has no attribute 'append'

Many2many fields should be updated using `|=` to add records, as the Python list
method `append` is not supported for relational fields.

[1]- https://github.com/odoo/enterprise/blob/5bff585cfa24940626b14cdeaeae07b50a931e94/pos_iot/wizard/auto_config_pos_iot.py#L55

sentry-6719710908

closes odoo/enterprise#89743

X-original-commit: 4307ff05d971877cac54fbd01aaca9fdbe2971f5
Signed-off-by: Max Whale (mawh) <mawh@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>