[FIX] sale_amazon: handle missing warehouse on creation
Currently, an error occurs when user tries to create a new amazon account on a
new company.

Steps to replicate:
- Install `sale_amazon`.
- Create a new company and switch to it.
- Go to Settings > Amazon account > Try to create a new account.

Error:
```
  File /home/odoo/odoo18/enterprise/sale_amazon/models/amazon_account.py, line 214, in create
    'location_id': parent_location_data[0]['view_location_id'][0],
IndexError: list index out of range
```

Cause:
- Whenever a new company is created, it doesnt have any warehouses [1] and
  amazon stock locations [2].
- This causes the `parent_location_data` to be an empty list and causes error at
  line [3].

Solution:
- Assigning the `location_id` if the `parent_location_data` exists.

[1]: https://github.com/odoo/enterprise/blob/23f085bdba333807a25a2d41214b25f474c7edf8/sale_amazon/models/amazon_account.py#L206-L210

[2]: https://github.com/odoo/enterprise/blob/23f085bdba333807a25a2d41214b25f474c7edf8/sale_amazon/models/amazon_account.py#L201-L204

[3]: https://github.com/odoo/enterprise/blob/23f085bdba333807a25a2d41214b25f474c7edf8/sale_amazon/models/amazon_account.py#L214

sentry-7086464738

closes odoo/enterprise#101636

X-original-commit: e36c53612a6b5860140ea5690e896afa3bf6ce74
Signed-off-by: Lionel Piraux (lipi) <lipi@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>