[FIX] account_reports: properly fold nested grouped lines
Steps to reproduce:
- Create an Account Group
- Create a new Account Report as follows:
  * Name: any
  * Lines:
    1. [test line]
      * Group By: partner_id,account_id
      * Expressions:
        1. [test expression]
          * Computation Engine: Odoo Domain
          * Formula: [('account_id.account_type', '=', 'asset_receivable')]
          * Subformula: sum
- Actions > Create Menu Item
- Open the new report
- Try to unfold/fold a partner line

Issue:
Folding will not fold the first child (representing the created account
group). Also, error will raise
```
Uncaught Promise > Got duplicate key in t-foreach: ~account.report~37|~account.report.line~255|{'groupby': 'partner_id'}~res.partner~4226|~account.group~90

Occured on odoo.nas.cpolar.cn on 2025-04-26 04:58:53 GMT

OwlError: Got duplicate key in t-foreach: ~account.report~37|~account.report.line~255|{'groupby': 'partner_id'}~res.partner~4226|~account.group~90
Error: Got duplicate key in t-foreach: ~account.report~37|~account.report.line~255|{'groupby': 'partner_id'}~res.partner~4226|~account.group~90
at AccountReport.template (eval at compile (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:13743:20), <anonymous>:138:49) (/web/static/lib/owl/owl.js:5752)
at App.callTemplate (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:11363:50) (/web/static/lib/owl/owl.js:3372)
at AccountReport.template (eval at compile (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:13743:20), <anonymous>:9:12) (/web/static/lib/owl/owl.js:5752)
at RootFiber._render (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:9774:38) (/web/static/lib/owl/owl.js:1783)
at RootFiber.render (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:9766:18) (/web/static/lib/owl/owl.js:1775)
at ComponentNode.render (https://odoo.nas.cpolar.cn/web/assets/debug/web.assets_web.js:10493:23) (/web/static/lib/owl/owl.js:2502)
```

Analysis:
Folding issues occurs because of a mismatch in the grouping markup quote
escape. If we don't have the very same string the controller cannot
properly recognize the parent line and then is unable to fold/unfold
properly.
This eventually led to the mentioned error at unfold as the backend will try
to generate the apparently missing lines to unfold, only to create
duplicate lines

opw-4754241

closes odoo/enterprise#92423

X-original-commit: 848c63113de20f1562585866784d11a4d371ba03
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>