[FIX] account_online_synchronization: Prevent transaction_details sanitization
This commit ensures that the transaction_details field in
account.bank.statement.line.transient is not sanitized when importing missing
transactions.

Before this commit:
- `transaction_details` was stored in an HTML field, which attempted to sanitize
the data.
- A recent change in Odoo Fin modified the data format from a stringified JSON
to a dictionary.
- As a result, the HTML field could not sanitize the dictionary and returned an
error: "Unknown error when sanitizing".

Fix:
- Prevent sanitization of `transaction_details` by setting `sanitize=False`.
- Convert the value on the fly from an html element to a json by using
`html2plaintext` and `json` library.

opw-4589740

closes odoo/enterprise#80042

X-original-commit: ed7eee1872b734166c060e34b770003929d8ffce
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>