[FIX] l10n_cl_edi: prevent date rollback when posting an invoice in tests
**Issue:**
```python
 File "/data/build/enterprise/l10n_cl_edi/models/account_move.py", line 744, in _l10n_cl_edi_post_validation
    raise UserError(
odoo.exceptions.UserError: The stamp date and time cannot be prior to the invoice issue date and time. TIP: check in your user preferences if the timezone is "America/Santiago"
```

**Cause:**
Posting an invoice at early local hours (e.g., 2025-12-11 04:00) is
converted by the Chilean timezone (America/Santiago) to the previous day
(e.g., 2025-12-10 19:30).

**Solution:**
- Freeze the test time at a stable CL-safe hour
- Add a fixed `invoice_date` aligned with the frozen timestamp

Runbot error: 234755

closes odoo/enterprise#102315

X-original-commit: 556a1c37bd4bc4f2d21c10e1448f5a34fe2b09cb
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>
Signed-off-by: Bommisetty Narendra (bona) <bona@odoo.com>