[FIX] l10n_be_hr_payroll_account: prevent error when salary rule is not found
Currently an issue occurs when the user tries to install
`10n_be_hr_payroll_account/account` after follow steps:

- Install `l10n_be_hr_payroll` and switch to `BE Company CoA`
- Go to Payroll > Configuration > Salary > Rules
- Delete `Mobility Budget Special Contribution`
- Error occurs when trying to install accounting

error: `ValueError: External ID not found in the system:
l10n_be_hr_payroll.cp200_employees_salary_mobility_budget_tax`

The salary rule mentioned above steps was added with commit [1], and the issue
also occurs if the database was created before commit [1] with a module
`l10n_be_hr_payroll` and the user tries to install the account after commit [1].

This commit fixes the issue by using `raise_if_not_found=False`, which prevents
an error from being raised when the salary rule is missing.

[1] - https://github.com/odoo/enterprise/commit/16c8a223beda4e4ebcf2c24f716687726f7230f3

sentry-6578747340

closes odoo/enterprise#92812

X-original-commit: 8b09795d2d0a2c8157731059816ddfb7187b2d1a
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>