[FIX] l10n_ke_edi_oscu_pos: fix traceback during pos payment validation
Steps to reproduce:
1. Install `l10n_ke_edi_oscu_pos`.
2. Set company to a Kenya (KE) company.
3. Open POS → Clothes shop → add a product → go to Payment
→ try to Validate → traceback occurs.

Issue:
- A traceback is raised when validating a payment in the POS screen.

`undefined
TypeError: Cannot read properties of undefined (reading 'services')
    at OrderPaymentValidation.beforePostPushOrderResolve`

Cause:
-  ` this.env` and `this.orm` is not directly accessible in
`OrderPaymentValidation`.

https://github.com/odoo/enterprise/blob/8ca771eb28a1fac13037c0d45e8d716d3dfc6ed2
/l10n_ke_edi_oscu_pos/static/src/app/utils/order_payment_validation.js#L7-L24

Solution:
- Use `this.pos.env` instead of `this.env`, and `this.pos.data.call` instead of
  `this.orm.call` to correctly access the environment and execute data calls
  during payment validation.

-Reference:

https://github.com/odoo/enterprise/blob/5a794a6e69ba884862b4a3f399143d1392caa6f0
/pos_barcodelookup/static/src/overrides/components/product_screen/
product_screen.js#L8-L10

opw - 5137557

closes odoo/enterprise#96284

Related: odoo/odoo#230069
Signed-off-by: David Monnom (moda) <moda@odoo.com>