[FIX] sign: use request's communication company to send
Problem: In a multi-company environment,
users are unable to send templates in non-default
companies despite them creating the template.
A traceback gets thrown because the template
is using the default company on the create user.

Purpose: The user should be able to send requests
from templates they created in any allowed companies.

Steps to Reproduce on Runbot:
[ADMIN]
1. Install Sign
2. Navigate to Settings > Sign > Enable "Sign Default Terms & Conditions"
3. Create another company and allow Marc Demo access

[Marc Demo]
1. Change to a non-default company
2. Try to send a signature request
(e.g. upload pdf to sign > send)
3. Traceback gets thrown
```
AccessError: Due to security restrictions, you are not allowed to access 'Companies' (res.company) records.

Records: BE Company CoA (id=2)
User: Marc Demo (id=6)

This restriction is due to the following rules:
- company rule employee

Note: this might be a multi-company issue.

Contact your administrator to request access if necessary.
Template: sign.sign_template_mail_request
Path: /t/table/tr[5]/t[1]/td/a
Node: <a t-att-href="\'%s/sign/terms\' % record.get_base_url()" class="text-dark"/>
```

opw-4706828

closes odoo/enterprise#91283

X-original-commit: 3ab88beb8e2e9df71fb2b9fac17f0e9d7d20d5dd
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>
Signed-off-by: Mylyna Hy (myhy) <myhy@odoo.com>