[FIX] l10n_it_xml_export: fix traceback if posting closing entry from dashboard
Currently a traceback is occurring when the user tries to post a journal entry
from journal dashborad.

Steps to reproduce:
1) Install `l10n_it_xml_export` and switch to IT company
2) Create a closing entry for the tax report
3) Open the miscellaneous Operations from Accounting Dashboard
4) Open the above-created entry by removing the default filter
5) Post the closing entry, a wizard opens.
6) Validate the values.
7) A traceback appears

Error:
"account.journal' object has no attribute '_get_report_options_from_tax_closing_entry'

Cause:
When the user tries to post the closing entry from the accounting dashboard,
its active_model is `account.journal`, and the active_id should be
the current id of the miscellaneous journal.

Then leads to the above traceback, since the method
`_get_report_options_from_tax_closing_entry` is available in account.move.

Solution:
To resolve this issue, we can browse the current move from the
`ctx['l10n_it_moves_to_post']`, since the value of the `l10n_it_moves_to_post` is
also self.ids which is the current active id for that closing entry.

opw-4783958

closes odoo/enterprise#91403

X-original-commit: 9c7465b59a95156e6c13d6a25c75fc8fd6fe2227
Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>