[FIX] documents: test incompatible with l10n_fr
test_upload_internal_multi_company_defaults was added in commit
9f66204e0cd0b2f19456f3bb0131d23e6d137b0b (PR #80060) but for databases with
l10n_fr_account installed, the test fails due to the user having another
company : base.demo_company_fr

This creates the following error message when running the tests:
```Py
FAIL: TestDocumentsControllers.test_upload_internal_multi_company_defaults
Traceback (most recent call last):
  File "/home/odoo/src/enterprise/documents/tests/test_controllers.py", line 953, in test_upload_internal_multi_company_defaults
    self.assertEqual(self.user_admin.company_ids, main_company | comp)
AssertionError: res.company(28, 1, 110) != res.company(1, 110)
```
with the following command :
```bash

python3 odoo-bin --addons-path="addons/,../enterprise/" -d test_4507424 -i documents,accountant,l10n_fr_account --test-tags .test_upload_internal_multi_company_defaults
```
(make sure to use the correct python3, odoo-bin, and addons-path)

This commit fixes the test by removing the constraint that self.user_admin can
only have 2 companies

After this commit, the test is successful with the same configuration and
execution command

opw-4700255
opw-4507424

closes odoo/enterprise#83163

X-original-commit: 2755be3a71864fe94a53127cea3afac5bbc7c453
Signed-off-by: Florian Charlier (flch) <flch@odoo.com>