[FIX] documents_(account,project): ensure referred tags exist
The server actions reference tags that might not exist in the database,
so we need to ensure they exist before loading the server actions during install.

To reproduce:
- Install Documents.
- Delete one or more of the referenced tags.
- Install documents_account.

This also happens during upgrades when the tags are missing and the module is
auto-installed.

```
ValueError: External ID not found in the system: documents.documents_tag_inbox
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-18.2/documents_account/data/ir_actions_server_data.xml:6, somewhere inside
<record id="ir_actions_server_create_vendor_bill" model="ir.actions.server" forcecreate="0">
```

closes odoo/enterprise#83924

X-original-commit: 0be3fb2661b14690f090776a2da4eb767e489ef2
Signed-off-by: Florian Charlier (flch) <flch@odoo.com>