[FIX] pos_avatax: remove dead reference of '_get_lines_eligible_for_external_taxes'
Since [this PR](https://github.com/odoo/enterprise/pull/82623),
defination of  `_get_lines_eligible_for_external_taxes` was removed but a
reference to it still remained, causing the following error when calling
the `_get_line_data_for_external_taxes` method:.

`AttributeError: 'pos.order' object has no attribute '_get_lines_eligible_for_external_taxes'`

Fix:
Removed reference to `_get_lines_eligible_for_external_taxes` from
`_get_line_data_for_external_taxes` at [1].

[1]: https://github.com/odoo/enterprise/blob/9a1544d19c1f5f3546c04022a11601df43199d10/pos_avatax/models/pos_order.py#L15-L18

sentry-6843827499

closes odoo/enterprise#95166

X-original-commit: da5ffdff28863e526036d74eb6b64f68a03242bb
Signed-off-by: Stéphane Vanmeerhaeghe (stva) <stva@odoo.com>
Signed-off-by: Het Patel (path) <path@odoo.com>