[FIX] hr_payroll: prevent error on adding salary inputs
Currently, an error occurs when user tries to add a salary input on a payslip.

Steps to replicate:
- Install `hr_payroll`.
- Go to any Employee payslip > Salary Inputs > Add Inputs.

Error:
`AttributeError: 'hr.payslip' object has no attribute 'structure_id'`

Cause:
- Error occurs after addition of a new [feature].
- The [code] tries to access `self.structure_id` on a record of `hr.payslip`,
  but since there’s no field named `structure_id`, it resulted in an error.

Solution:
- Used the field `struct_id` that keeps the record of linked `hr.payroll.structure()`.

[feature]: https://github.com/odoo/enterprise/pull/98151
[code]: https://github.com/odoo/enterprise/blob/eda93203ec8da207768357ae91132a49881a2978/hr_payroll/models/hr_payslip.py#L2159

No ID

closes odoo/enterprise#100966

Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>