[FIX] l10n_be_reports: prevent import crash in contacts due to tag access check
Steps to reproduce:
1. Install contact and l10n_be_reports
2. Export any contact with external_id and tag (category_id) columns.
3. Edit the exported file and set category_id to blank.
4. Attempt to import the modified file.

Issue:
  Import fails with the error:
  TypeError: 'bool' object is not iterable

Cause:
  The write override in l10n_be_reports checks for removal of the protected tag
  '281.50' using:
  vals.get('category_id', [])
  However, when category_id is False (as in the import case),
  vals.get('category_id', []) returns False, causing the
  iteration to fail with a TypeError.

Solution:
  vals.get('category_id') or []
  This ensures a safe fallback to an empty list in case the value is False.

opw-4717387

closes odoo/enterprise#88201

X-original-commit: b886fc70591f5ca846db93cf16ff960686106e08
Signed-off-by: Ruben Gomes (rugo) <rugo@odoo.com>
Signed-off-by: Piyush Sharma (pish) <pish@odoo.com>