[IMP] documents_hr_contract: prevent error when field is missing
The system will crash with an error when the user tries to validate the
signature.

Steps to produce:
- Install `Sign, Employee Contracts, and Documents` apps with demo data.
- Go to Apps and uninstall the `hr_sign`module.
- Send any employee a sign request for a document.
- When the employee tries to validate and send the document, the error appears.

Error:
`KeyError: 'sign_request_ids'
ValueError: Invalid field hr.employee.sign_request_ids in condition ('sign_request_ids', 'in', [1])`

Cause:
- When `sign` route is called, then we try to search field `sign_request_ids` in
  `hr_employee`. but we can see the field `sign_request_ids` is defined in
  `hr_sign` module.
- And user removed the `hr_sign` module, so the field no longer exists.
  in the hr_employee model.

Solution:
- If the field is missing, return the result.

sentry-6819182542

closes odoo/enterprise#101012

X-original-commit: 3cbb804e9f46f892e0b742633537798ff973c636
Signed-off-by: Florian Charlier (flch) <flch@odoo.com>
Signed-off-by: Krishna Arvindkumar Patel (krip) <krip@odoo.com>