[FIX] sale_renting: remove parent dependency from pricing view
Versions
--------
- 17.0+

Steps
-----
1. Go to Automation Rules;
2. create a new automation;
3. set model to `product.pricing`;
4. in one of the filters, check the record(s) that fit in the domain.

Issue
-----
> EvalError: Can not evaluate python expression: (bool(parent.product_variant_count < 2))
> Error: Name 'parent' is not defined

Cause
-----
`parent` is not defined because the `product_variant_ids` field in the
view does not have a parent field to evaluate.

Solution
--------
Remove the `parent` checks.

opw-4788215

closes odoo/enterprise#86494

X-original-commit: 55edebcea9da56f52f9681fc2eddea51925d9106
Signed-off-by: Levi Siuzdak <sile@odoo.com>