[FIX] planning: prevent error when exporting ICS for shift without assigned employee
Currently, an error occurs when a user tries to export a calendar invite (ICS)
for a planning shift that has no assigned resource.

Steps to reproduce:

- Install the planning module.
- Go to Planning > New, and click Publish & Send.
- Enable developer mode and go to Settings > Technical > Email > Emails.
- Open the latest email record and click iCal/Outlook.

Error:
AttributeError: 'bool' object has no attribute 'upper'

Root Cause:
At [1], when no employee is assigned to the shift, slot.employee_id is empty, so
slot.employee_id.tz is False, which leads to an error.

This commit ensures a valid timezone is always used by selecting the current
user's timezone or 'UTC' when the shift has no assigned employee.

[1]:
https://github.com/odoo/enterprise/blob/13ce65b8ca61f9a825f2876e2727cddfae83f894/planning/controllers/main.py#L355

sentry-6781639319

closes odoo/enterprise#93141

X-original-commit: b3c6e62e7517c867d8e20b79af6352c8572461a1
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>