[FIX] sign: handled context not to be response object
The system fails when ir. qweb. _ render () is called with a values argument
that is not a dictionary but a `Response ' object.

Steps to Produce:

1. Open Sign Module > Templates > Click on the Sign Now button of any template.
2. Copy url > delete sign reques > paste url in websie
3. The error will be visible on the terminal.

Error:
AttributeError: 'Response' object has no attribute 'copy'

Solution:
 - Updated get_document() to check if context is not a dict.
 - If not, the method now safely returns request.not_found().

sentry - 6521023695

closes odoo/enterprise#85217

X-original-commit: 35a40247ab73ea2c2cec8edb07f5a9d39b979c92
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>
Signed-off-by: Krishna Arvindkumar Patel (krip) <krip@odoo.com>