[FIX] industry_fsm_sale: prevent error on installing module
Currently a ParseError is arising when the user installs the 'industry_fsm_sale'
module after deleting the 'Services' in Product Categories/Configuration.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Product Categories > Delete 'Services'
- Now install 'industry_fsm_sale' module

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError
while parsing /home/odoo/src/enterprise/saas-18.3/industry_fsm_sale/data/industry_fsm_data.xml:5, somewhere inside
<record id="field_service_product" model="product.product">
            <field name="name">Field Service</field>
            <field name="project_id" search="[('id', '=?', ref('industry_fsm.fsm_project', raise_if_not_found=False)), ('is_fsm', '=', True)]"/>
            <field name="service_tracking">task_global_project</field>
            <field name="type">service</field>
            <field name="categ_id" ref="product.product_category_services"/>

The error occurs because the user deleted 'Services' in Product Categories, and
then tried to install the other module.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6377659355

closes odoo/enterprise#89713

X-original-commit: 32335bdf7c083217085a9c6cfa20d67280e472cc
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>