[FIX] web_studio: Fix traceback in studio
step to reproduce
1. createdb with installing l10n_co_reports in 18.0
2. and install web_studio
3. open studio in customer invoice menu and tap
on Daily Journal report

below traceback is rasing
for fixing it adding in blacklist report
so it won't show in studio as I have checked
the purpose this report to show the report using
accounting report
https://github.com/odoo/enterprise/commit/e7efdb09742c434f1f72ec9c8f619038c470b464

```
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/18.0/odoo/http.py", line 1963, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/odoo/odoo/odoo/18.0/odoo/service/model.py", line 156, in retrying
    result = func()
  File "/home/odoo/odoo/odoo/18.0/odoo/http.py", line 1930, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/odoo/odoo/18.0/odoo/http.py", line 2178, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/odoo/odoo/18.0/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/odoo/odoo/18.0/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/odoo/enterprise/18.0/web_studio/controllers/report.py", line 499, in load_report_editor
    report_qweb = self._get_report_qweb(report)
  File "/home/odoo/odoo/enterprise/18.0/web_studio/controllers/report.py", line 636, in _get_report_qweb
    render_context = report_safe_cr._get_rendering_context(report_safe_cr, [0], {"studio": True})
  File "/home/odoo/odoo/enterprise/18.0/web_studio/models/ir_actions_report.py", line 44, in _get_rendering_context
    ctx = super()._get_rendering_context(report, docids, data)
  File "/home/odoo/odoo/odoo/18.0/addons/account/models/ir_actions_report.py", line 94, in _get_rendering_context
    data = super()._get_rendering_context(report, docids, data)
  File "/home/odoo/odoo/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1105, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
  File "/home/odoo/odoo/enterprise/18.0/l10n_co_reports/report/libro_diario_report.py", line 17, in _get_report_values
    report = self.env['account.report'].browse(options['report_id'])
TypeError: 'NoneType' object is not subscriptable
```

opw-4608924
upg-2733166

closes odoo/enterprise#83263

X-original-commit: ce403718e0f5ad5d2ff2ec6ee529601b52dd5a59
Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>
Signed-off-by: Sanchit Gupta (sagu) <sagu@odoo.com>