[FIX] account_external_tax, sale_external_tax: fix Avatax company invoice/SO
Issue: A traceback occurs when attempting to create an invoice or sales order for a customer whose fiscal position is set to Automatic Tax Mapping in Brazilian accounting.

File "/home/odoo/src/enterprise/account_external_tax/models/account_move.py", line 18, in _compute_tax_totals
subtotal = tax_totals['subtotals'][0]
~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Steps to reproduce:
- Have Brazilian localization (including EDI modules) with Avatax configuration.
- Create a new Sales Order or Invoice and:
  - Use a contact with a fiscal position set to "Automatic Tax Mapping (Avalara Brazil)", or
  - Set the fiscal position to that on the SO or invoice itself.
- Observe the traceback as described in the ticket.

Explanation: In account_move/sale_order from the modules account_external_tax/sale_external_tax, the method _compute_tax_totals attempted to compute the tax totals when there were no account move lines (tax_totals['subtotals'] is empty), which results in the out of range traceback. The Brazilian Automatic Tax Mapping is computed externally, which is why it triggered this issue.

opw-4256191

closes odoo/enterprise#73378

X-original-commit: 732a00866175cce11da7b92c6d1d119217b49174
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>