[FIX] planning: hide auto plan option in case of unscheduled shift
Step to reproduce:

1. Install sale_planning module
2. Create a product (Sales -> Products):
     - Set Product Type to Service
     - Enable Plan Services
     - Assign both a Planning Role and resources.
3. Create a sales order for this product.
4. Confirm the Sales Order.
5. Click the "To Plan" button.
6. Switch to List View.
7. Open the Unscheduled Shifts (None) section.
8. Try to generate an Auto Plan.

Issue:

A traceback is raised during auto-planning when the start_datetime or
end_datetime on the planning slot is missing.

AttributeError: 'bool' object has no attribute 'astimezone'

Cause:

The auto_plan_ids method assumes that shifts have valid start_datetime and
end_datetime. However, for unscheduled shifts, these fields can be
empty (i.e., False), causing the error.

Solution:
we hide the auto-plan button, in case we do not have startdate
or enddate

opw-4812509

co-authored by: Ajit Singh (aksi@odoo.com)

closes odoo/enterprise#92694

X-original-commit: 751e65da66fc8968807904d233cf9488bbdc4052
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>