[FIX] sale(,_stock)_renting: remove new line in context
Issue
-----

When opening the rental schedule view from the `qty_at_date` widget or
from the form view of a product, an error occurs:

```
Traceback (most recent call last):
  ...
  File "/data/build/enterprise/sale_stock_renting/models/product_product.py", line 162, in action_view_rentals
    result = super().action_view_rentals()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/enterprise/sale_renting/models/product_product.py", line 66, in action_view_rentals
    context: dict = ast.literal_eval(action.get('context', '{}'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/odoo/_monkeypatches/ast.py", line 28, in literal_eval
    return orig_literal_eval(expr)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 66, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    {
IndentationError: unexpected indent
```

Introduced by https://github.com/odoo/enterprise/pull/87234

Fix
---

This commit fixes the action `sale_renting.action_rental_order_schedule`
by removing the leading newline in the action context, which caused the
evaluation to fail.

task-4720184

closes odoo/enterprise#94029

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>