[FIX] appointment_account_payment: prevent error on installing module
Currently a 'ParseError' arises when the user installs the
'appointment_account_payment' module after deleting the 'Service' category in
'Invoicing'.

Steps to reproduce:
- Install 'Invoicing' application (without demo data)
- Invoicing > Configuration > Categories > Delete 'Services'
- Now install 'appointment_account_payment' module

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/enterprise/saas-18.1/appointment_account_payment/data/product_data.xml:3, somewhere inside
<record id="default_booking_product" model="product.product">
        <field name="name">Booking Fees</field>
        <field name="standard_price">0.00</field>
        <field name="uom_id" ref="uom.product_uom_unit"/>
        <field name="list_price">50.00</field>
        <field name="type">service</field>
        <field name="purchase_ok" eval="False"/>
        <field name="categ_id" ref="product.product_category_services"/>
        <field name="image_1920" type="base64" file="appointment_account_payment/static/src/img/booking_product.png"/>
    </record>

The error occurs because the user deleted the category and then installed the
'appointment_account_payment' module, which references the missing product
category.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6298992760

closes odoo/enterprise#79614

X-original-commit: bb2138707d755ca0989efee393893b3ae6008d7c
Signed-off-by: Jérémy Hennecart (jeh) <jeh@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>