[FIX] ai: prevent error when parsing pivot measures
The system crashes with an error when a user adds a prompt in AI and searches.

Steps to produce:
- Install the `Sales and AI` module with demo data.
- Go to sales and click on the AI button on top.
- Add query that used pivot view like `Top 5 sales reps by revenue also make
  pivot view`.
- Try multiple times (error only comes in terminal).

Error:
ValueError: Measure 'price_subtotal:sum' not found in model 'sale.report' for menu ID 331.

Cause:
- Here at [1], we split the measure_str and assign the first element to
  `measure_name`.
- At [2], we try to find a field in the model using this `measure_name`, which
  fails.
- The issue is that `measure_name` can contain both the `field` and its
  `aggregation` function (e.g., product_qty:sum), which is not a valid field.

Solution:
- In this PR, a new method `validate_measures` has been added to ensure that
  the provided measures are valid and properly defined.

[1]: https://github.com/odoo/enterprise/blob/f838bbd0ce425d24444b510e49752c3da8068712/ai/models/ai_agent.py#L1244-L1245

[2]: https://github.com/odoo/enterprise/blob/f838bbd0ce425d24444b510e49752c3da8068712/ai/models/ai_agent.py#L1264-L1265

sentry-6917511363,6915439025

closes odoo/enterprise#96247

Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>