[FIX] pos_pricer: remove compute from field
The compute method was removed in this commit, but is declared in the field.

Traceback:
AttributeError: 'product.product' object has no attribute '_compute_pricer_display_price'

This commit removes the compute declaration from the field.

commit : https://github.com/odoo/enterprise/pull/66351/commits/70d96c44bb834ecbe89b5720ae18a93038301796#diff-2f3d348951d6293f7e805819d7053ac4ec65994bbacc829dac5dc68b00c932c>

sentry-6547636163

closes odoo/enterprise#84335

X-original-commit: d9da99ccac1e7107ecc0ff094516deb2dcf4b9f9
Signed-off-by: Yaroslav Soroko (yaso) <yaso@odoo.com>