[FIX] sign_emsigner: fix error after successful Aadhaar signing
Before this commit, after successfully signing with Aadhaar and returning to
Odoo,
"sign_request = request_item_sudo.sign_request_id
UnboundLocalError: local variable 'request_item_sudo' referenced before
assignment"
This happened because request_item_sudo was not defined.

This commit fixes the issue by correcting the variable name so it’s properly
defined before use.

closes odoo/enterprise#92161

Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>