[FIX] website_sale_renting: prevent frontend tracebacks on invalid dates
Versions
--------
- 17.0+

Steps
-----
1. Have `website_event_sale` but not `stock` installed;
2. create an event with a ticket;
3. make the ticket's product rentable;
4. change ticket's product type to Goods;
5. publish the event to website;
6. register for the event via website;
7. go to payment.

Issue
-----
AttributeError: 'bool' object has no attribute 'tzinfo'

Cause
-----
Having odd configurations like rentable tickets creates rental orders
without rental dates, leading to unhandled errors.

Solution
--------
While rentable event tickets doesn't make enough sense to make it work,
we can still improve the error handling to prevent showing tracebacks to
the client.

opw-5207045

closes odoo/enterprise#101936

X-original-commit: a97ed6dbc7e67f247cecb2856c8af1ef370cb0fe
Signed-off-by: Patricia Daloze (pda) <pda@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>