[FIX] sign: allow to link records without name
Before this commit the following traceback could be observed if a record
did not had any name field and was linked to a sign request:

``
2024-12-16 08:41:09,063 27947 INFO 18.0-sale_commission-next-sub-arj odoo.addons.mail.models.mail_render_mixin: Failed to render template: 683
Traceback (most recent call last):
  File "<683>", line 44, in template_683
  File "<683>", line 12, in template_683_content
AttributeError: 'x_toto' object has no attribute 'name'. Did you mean: '_name'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arj/PycharmProjects/worktree/18.0/odoo/addons/mail/models/mail_render_mixin.py", line 415, in _render_template_qweb_view
    render_result = self.env['ir.qweb']._render(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arj/PycharmProjects/worktree/18.0/odoo/odoo/tools/profiler.py", line 306, in _tracked_method_render
    return method_render(self, template, values, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arj/PycharmProjects/worktree/18.0/odoo/odoo/addons/base/models/ir_qweb.py", line 601, in _render
    result = ''.join(rendering)
             ^^^^^^^^^^^^^^^^^^
  File "<683>", line 52, in template_683
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'x_toto' object has no attribute 'name'
Template: 683
Path: /t/p/t
Node: <t t-esc="request.reference_doc.name"/>

```

closes odoo/enterprise#75672

Opw-ticket: 4366583
X-original-commit: 682b1c8cf399785b6ed40bfe674b188c6932ae71
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>