[FIX] l10n_be_reports: fix day out of range traceback
```
File "/tmp/tmpm_3a__2e/migrations/account_reports/saas~18.3.1.0/end-account-returns.py", line 340, in migrate
    generate_or_refresh_all_returns(company)
  File "/home/odoo/src/enterprise/19.0/account_reports/models/account_return.py", line 228, in _generate_or_refresh_all_returns
    self._generate_all_returns(fiscal_country.code, company, domestic_tax_unit)
  File "/home/odoo/src/enterprise/19.0/l10n_be_reports/models/account_return.py", line 24, in _generate_all_returns
    super()._generate_all_returns(country_code, main_company, tax_unit=tax_unit)
  File "/home/odoo/src/enterprise/19.0/account_reports/models/account_return.py", line 281, in _generate_all_returns
    report_type._try_create_returns_for_fiscal_year(main_company, tax_unit=tax_unit)
  File "/home/odoo/src/enterprise/19.0/account_reports/models/account_return.py", line 353, in _try_create_returns_for_fiscal_year
    period_date_from, period_date_to = self._get_period_boundaries(main_company, date_pointer)
  File "/home/odoo/src/enterprise/19.0/account_reports/models/account_return.py", line 530, in _get_period_boundaries
    start_day, start_month = self._get_start_date_elements(company_id)
  File "/home/odoo/src/enterprise/19.0/l10n_be_reports/models/account_return.py", line 16, in _get_start_date_elements
    fiscal_year_date = date(2025, int(main_company.fiscalyear_last_month), main_company.fiscalyear_last_day)
ValueError: day is out of range for month
```
```
(Pdb) main_company
res.company(3,)
(Pdb) main_company.fiscalyear_last_month
'2'
(Pdb) main_company.fiscalyear_last_day
29
(Pdb) date_from
datetime.date(2025, 3, 1)
```
- During the migration process the system calls _generate_or_refresh_all_returns
https://github.com/odoo/upgrade/blob/e20a9e2edec4441b2c7aa5858db2a53fb2e9b215/migrations/account_reports/saas~18.3.1.0/end-account-returns.py#L340
which internally uses _get_start_date_elements
https://github.com/odoo/enterprise/blob/ebdc2fe2ade72b1505dac5490b7df2a1d06fcb4b/l10n_be_reports/models/account_return.py#L14
to compute the fiscal year start date.
The customer has configured fiscalyear_last_month = February and
fiscalyear_last_day = 29 Because of this configuration, the method attempts
to construct 29th February 2025, which is invalid since 2025 is not a leap year.
The issue occurs because the method uses a hardcoded year (2025)
https://github.com/odoo/enterprise/blob/ebdc2fe2ade72b1505dac5490b7df2a1d06fcb4b/l10n_be_reports/models/account_return.py#L16
instead of determining the year dynamically.
- I reviewed implementations in other localizations and found that this logic
https://github.com/odoo/enterprise/blob/ebdc2fe2ade72b1505dac5490b7df2a1d06fcb4b/l10n_uk_reports/models/account_return.py#L33, https://github.com/odoo/enterprise/blob/ebdc2fe2ade72b1505dac5490b7df2a1d06fcb4b/l10n_nz_reports/models/account_return.py#L8
already been corrected there to compute the appropriate start date dynamically.
- I’ve updated this localization to follow the improved implementation used in
other countries, so the start-date calculation now works correctly in all cases,
including leap years and any fiscal year settings the customer may configure.

opw-5249243

closes odoo/enterprise#99701

X-original-commit: b1510ac80c8ea8fded0c10d09ceea304859ea281
Signed-off-by: Sven Führ (svfu) <svfu@odoo.com>
Signed-off-by: Karna Modasiya (kmod) <kmod@odoo.com>