[FIX] pos_settle_due: prevent error on installing module
Currently a ParseError is arising when the user installs the 'pos_settle_due'
module after deleting the 'Services' in Product Categories/Configuration.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Product Categories > Delete 'Services'
- Now install 'pos_settle_due' module

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/enterprise/saas-18.3/pos_settle_due/data/pos_settle_due_data.xml:22, somewhere inside
<record id="product_product_settle_invoice" model="product.product">
            <field name="name">Settle Invoice</field>
            <field name="categ_id" ref="product.product_category_services"/>
            <field name="type">service</field>
            <field name="weight">0.00</field>
            <field name="available_in_pos">False</field>
            <field name="taxes_id" eval="[]"/>
        </record>

The error occurs because the user deleted 'Services' in Product Categories, and
then tried to install the other module.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6377659355

closes odoo/enterprise#86664

X-original-commit: 61e5d2ca1f73d3ff60bda9044544b110fbeb22e6
Signed-off-by: Vlad Stroia (vlst) <vlst@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>