[FIX] web_studio: prevent generating invalid field nodes
Steps to reproduce
==================

- Install web_studio,hr_timesheet
- Edit the report `hr_timesheet.report_timesheet`
- Insert a field below the "Date" header
- Preview the report

```
QWebException: Error while render the template
KeyError: 'undefined'
Template: hr_timesheet.timesheet_table
Path: /t/div/div/table/thead/tr/th[2]/span/span
Node: <span t-field="undefined.amount"/>
```

Cause of the issue
==================

We have the cursor inside this block:

https://github.com/odoo/odoo/blob/97792fff389ac5621d77485a4179e16dc99c26f7/addons/hr_timesheet/report/report_timesheet_templates.xml#L8-L26

It means we are outside the header/footer and outside any t-foreach.

`getDefaultVariable` will not find any result

Solution
========

We disable the `/Field` and `/Dynamic Table` when we don't have a
defaultVariable

opw-5043719

closes odoo/enterprise#102311

X-original-commit: 33c6c9c6d5e42dd1cd74016725b07b17680d47d8
Signed-off-by: Lucas Perais (lpe) <lpe@odoo.com>
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>